version: '3.9'
services:
  php-env:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8088:80
    depends_on:
      - db_mysql
  # imam
  db_mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: swiss_collection2
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8089:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_mysql
# volumes:
#   db_mysql:

# imam
